package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum LCDSLOT {
  SLOT1("SLOT1", false),
  SLOT2("SLOT2", false),
  SLOT3("SLOT3", false);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final boolean myValue;
  LCDSLOT(String name, boolean value) {
    myName = name;
    myValue = value;
  }
  public boolean getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Boolean.toString(myValue);
  }
  public static List<LCDSLOT> getConstants() {
    List<LCDSLOT> list = ListSequence.fromList(new LinkedList<LCDSLOT>());
    ListSequence.fromList(list).addElement(LCDSLOT.SLOT1);
    ListSequence.fromList(list).addElement(LCDSLOT.SLOT2);
    ListSequence.fromList(list).addElement(LCDSLOT.SLOT3);
    return list;
  }
  public static LCDSLOT getDefault() {
    return null;
  }
  public static LCDSLOT parseValue(String value) {
    if (value == null) {
      return LCDSLOT.getDefault();
    }
    if (value.equals(LCDSLOT.SLOT1.getValueAsString())) {
      return LCDSLOT.SLOT1;
    }
    if (value.equals(LCDSLOT.SLOT2.getValueAsString())) {
      return LCDSLOT.SLOT2;
    }
    if (value.equals(LCDSLOT.SLOT3.getValueAsString())) {
      return LCDSLOT.SLOT3;
    }
    return LCDSLOT.getDefault();
  }
}
