package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum SelectType {
  random("random", "random"),
  linear("linear", "linear");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private SelectType(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<SelectType> getConstants() {
    List<SelectType> list = ListSequence.fromList(new LinkedList<SelectType>());
    ListSequence.fromList(list).addElement(SelectType.random);
    ListSequence.fromList(list).addElement(SelectType.linear);
    return list;
  }
  public static SelectType getDefault() {
    return SelectType.random;
  }
  public static SelectType parseValue(String value) {
    if (value == null) {
      return SelectType.getDefault();
    }
    if (value.equals(SelectType.random.getValueAsString())) {
      return SelectType.random;
    }
    if (value.equals(SelectType.linear.getValueAsString())) {
      return SelectType.linear;
    }
    return SelectType.getDefault();
  }
}
